# Ensure only packages released at least 1 day ago can be installed.
minimumReleaseAge: 1440

nodeLinker: "hoisted"

allowBuilds:
  "@sentry/cli": true
  esbuild: false
  msgpackr-extract: false
  react-native-audio-browser@https://codeload.github.com/MissingCore/react-native-audio-browser/tar.gz/05f7af440edc29222d12a0acc58234f5cb51433d: true
  unrs-resolver: false

minimumReleaseAgeExclude:
  - "@missingcore/react-native-metadata-retriever@4.0.0-beta.1"
  - react-native-reanimated@4.5.1

patchedDependencies:
  "@lodev09/react-native-true-sheet": "patches/@lodev09__react-native-true-sheet.patch"
  react-native-android-widget: "patches/react-native-android-widget.patch"
