# Ensure only packages released at least 1 day ago can be installed.
minimumReleaseAge: 1440

nodeLinker: "hoisted"

allowBuilds:
  "@missingcore/react-native-metadata-retriever@https://codeload.github.com/MissingCore/react-native-metadata-retriever/tar.gz/1e80ada9b199026bf47d3cf23187b5384368a622": true
  "@sentry/cli": true
  esbuild: false
  msgpackr-extract: false
  react-native-audio-browser@https://codeload.github.com/MissingCore/react-native-audio-browser/tar.gz/05f7af440edc29222d12a0acc58234f5cb51433d: true
  unrs-resolver: false

minimumReleaseAgeExclude:
  - "@missingcore/react-native-metadata-retriever@3.2.1"

patchedDependencies:
  "@lodev09/react-native-true-sheet": "patches/@lodev09__react-native-true-sheet.patch"
  react-native-android-widget: "patches/react-native-android-widget.patch"
