name: "ðŸ› Bug Report"
description: "Report a reproducible bug in Music"
labels: ["Bug", "needs review"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this entire form. The most important piece of information are the actions that led to this issue.
  - type: input
    attributes:
      label: What device did this occur on?
    validations:
      required: true
  - type: input
    attributes:
      label: What version of Android is your device running?
    validations:
      required: true
  - type: input
    attributes:
      label: App Version
      description: |
        List the app version you are currently using. This can be found in:
          - The "Settings" page in the app.
          - In the "App Info" page for Music on your device (`Settings > Apps > Music` then scroll down).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Summary
      description: |
        Clearly describe and list out the actions that led to this issue. Include any video or screenshots showing a reproduction of this issue.
    validations:
      required: true
