name: Play Store Review
on:
  workflow_dispatch:

jobs:
  buildAAB:
    name: build AAB from current content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: ./.github/actions/setup

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 17

      - name: Add upload key secrets for signing APKs
        run: |
          git submodule update --init --recursive
          echo "${{ secrets.RELEASE_CRED }}" >> ./android/gradle.properties

      - name: Build upload keystore `.jks` file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "keystore.jks"
          fileDir: "./android/app"
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Clean generated builds
        run: rm -rf android/app/build/generated/

      - name: Build and sign app bundle with Gradle
        run: cd android && chmod +x gradlew && ./gradlew bundleRelease

      # Save `.aab` as artifact before upload to Play Console incase upload fails.
      - name: Save AAB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: outputAAB
          path: android/app/build/outputs/bundle/release/*.aab

      - name: Upload AAB to Google Play Console "Internal Testing" track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.cyanchill.missingcore.music
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          # No need for `changesNotSentForReview: true` as internal track shouldn't
          # get reviewed.
          track: internal
